version: '3'
services:
  clydetapot:
    container_name: 'ClydeTapBot'
    build:
      context: .
    stop_signal: SIGINT
    restart: unless-stopped
    command: "python3 main.py -a 1"
    environment:
    - TZ=Europe/Chisinau
    volumes:
      - .:/app